### ISSUE TITLE
Error when installing psdconvert via PIP?

### ISSUE THREAD

**Issue by Obliveater95** [sfneal/psdconvert#5]
Getting the below error when trying to install it using pip? Seems to be a problem with the package and not my installation of pip but I'm no expert in these things, so please let me know if it was something I did wrong!

```
C:\Users\oblive>pip install psdconvert
Defaulting to user installation because normal site-packages is not writeable
Collecting psdconvert
  Downloading psdconvert-1.0.0.tar.gz (2.9 kB)
  Preparing metadata (setup.py) ... done
Collecting psd_tools3>=1.8.2
  Downloading psd-tools3-1.9.2.tar.gz (73 kB)
     ---------------------------------------- 73.1/73.1 kB 2.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\oblive\AppData\Local\Temp\pip-install-76uy32_1\psd-tools3_e12a7057b4f14b0398a18bcc1c107c17\setup.py", line 18, in <module>
          version=get_version(),
                  ^^^^^^^^^^^^^
        File "C:\Users\oblive\AppData\Local\Temp\pip-install-76uy32_1\psd-tools3_e12a7057b4f14b0398a18bcc1c107c17\setup.py", line 12, in get_version
          with open(filename, 'rb') as fp:
               ^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\oblive\\AppData\\Local\\Temp\\pip-install-76uy32_1\\psd-tools3_e12a7057b4f14b0398a18bcc1c107c17\\psd_tools\\_version.py'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Andrej730** [comment]
In theory will be installable with `pip install git+https://github.com/sfneal/psdconvert.git` after #6 #7
